- name: Setup vpn server on rhel families
  hosts: 127.0.0.1
  become: true
  become_user: root
  vars:
    - rhel_user: almalinux
  tasks:
    - name: create {{ rhel_user }} user and attach sudo permission
      ansible.builtin.user:
        shell: /bin/bash
        name: {{ rhel_user }}
        groups: wheel
        append: yes

    - name: create .ssh folder
      ansible.builtin.file:
        path: "/home/{{ rhel_user }}/.ssh/"
        owner: {{ rhel_user }}
        group: {{ rhel_user }}
        mode: '0740'
        state: directory

    - name: create .authorized_keys
      ansible.builtin.file:
        path: "/home/{{ rhel_user }}/.ssh/authorized_keys"
        owner: {{ rhel_user }}
        group: {{ rhel_user }}
        mode: '0400'
        state: touch

    - name: add ssh pubkey
      ansible.builtin.blockinfile:
        marker: ""
        path: "/home/{{ rhel_user }}/.ssh/authorized_keys"
        owner: {{ rhel_user }}
        group: {{ rhel_user }}
        mode: '0400'
        block: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH/jpMd00hSkXILXNNvzic+PERIvou28UikpR7ayqgxo ed25519_04/04/22

    - name: create motd value
      ansible.builtin.blockinfile:
        marker: ""
        path: "/home/{{ rhel_user }}/.bashrc"
        block: |
          ### CUSTOM BASH
          HISTTIMEFORMAT="%d/%m/%Y %T "
          PS1='\[\033[01;31m\]\u\[\033[01;33m\]@\[\033[01;36m\]\h \[\033[01;33m\]\w \[\033[01;35m\]$ \[\033[00m\]'

    - name: create sudoers file
      ansible.builtin.file:
        path: "/etc/sudoers.d/99-newuser"
        state: touch

    - name: create sudoers permission with no password authorities
      ansible.builtin.blockinfile:
        marker: ""
        path: "/etc/sudoers.d/99-newuser"
        block: |
          # User rules for {{ rhel_user }}
          {{ rhel_user }} ALL=(ALL) NOPASSWD:ALL

    - name: installing depedencies
      ansible.builtin.dnf:
        name:
          - epel-release
          - python3
          - bash-completion
          - golang
          - tmux
          - firewalld
          - rsyslog
          - wget 
          - nano 
          - tar
        state: latest

    - name: create motd banner file
      ansible.builtin.file:
        path: "/etc/motd"
        state: touch

    - name: create motd value
      ansible.builtin.blockinfile:
        marker: ""
        path: "/etc/motd"
        block: |
          ---------------------------------------------------------
          ---------------------------------------------------------

                            >>> VPN Production <<<
          If it's not necessary, please don't shut down the VPS.

          ---------------------------------------------------------
          ---------------------------------------------------------

    - name: deleting unsecure config ssh
      args:
        executable: /bin/bash
      ansible.builtin.shell: |
        sed -i '/PasswordAuthentication/d' /etc/ssh/sshd_config
        sed -i '/MaxAuthTries/d' /etc/ssh/sshd_config
        sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
        sed -i '/PubkeyAuthentication/d' /etc/ssh/sshd_config

    - name: hardening ssh
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        marker: ""
        block: |
          Match User {{ rhel_user }}
          MaxAuthTries 2
          PermitRootLogin no
          PubkeyAuthentication yes
          PasswordAuthentication no

    - name: upgrade latest mainline kernel
      args:
        executable: /bin/bash
      ansible.builtin.shell: |
        sudo dnf -y install https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
        sudo rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
        sudo dnf --enablerepo=elrepo-kernel install -y kernel-ml
        sudo dnf --enablerepo=elrepo-kernel install -y kernel-ml-{devel,headers} --allowerasing
